services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-si_ketuk_pintu}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "127.0.0.1:${POSTGRES_EXTERNAL_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - si-ketuk-pintu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 25s

#  backend:
#    image: ${BACKEND_IMAGE:-ghcr.io/tnnz20/si-ketuk-pintu/backend:latest}
#    restart: unless-stopped
#    env_file:
#      - .env
#    ports:
#      - "127.0.0.1:${BACKEND_EXTERNAL_PORT:-8081}:8080"
#    volumes:
#      - uploads_data:/app/uploads
#    networks:
#      - si-ketuk-pintu-net
#    depends_on:
#      postgres:
#        condition: service_healthy

#  frontend:
#    image: ${FRONTEND_IMAGE:-ghcr.io/tnnz20/si-ketuk-pintu/frontend:latest}
#    restart: unless-stopped
#    ports:
#      - "127.0.0.1:${FRONTEND_PORT:-5173}:80"
#    networks:
#      - si-ketuk-pintu-net
#    depends_on:
#      - backend

networks:
  si-ketuk-pintu-net:
    driver: bridge

volumes:
  postgres_data:
#  uploads_data: