ALTER TABLE administrators
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE BIGINT USING (EXTRACT(EPOCH FROM created_at) * 1000)::BIGINT,
    ALTER COLUMN updated_at TYPE BIGINT USING (EXTRACT(EPOCH FROM updated_at) * 1000)::BIGINT,
    ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT;

ALTER TABLE visit_requests
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN tanggal_kunjungan TYPE BIGINT
        USING ((EXTRACT(EPOCH FROM (tanggal_kunjungan::TIMESTAMP AT TIME ZONE 'Asia/Makassar')) * 1000)::BIGINT),
    ALTER COLUMN jam_kunjungan TYPE BIGINT
        USING ((EXTRACT(EPOCH FROM jam_kunjungan) * 1000)::BIGINT - 28800000),
    ALTER COLUMN created_at TYPE BIGINT USING (EXTRACT(EPOCH FROM created_at) * 1000)::BIGINT,
    ALTER COLUMN updated_at TYPE BIGINT USING (EXTRACT(EPOCH FROM updated_at) * 1000)::BIGINT,
    ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT;

ALTER TABLE attachments
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE BIGINT USING (EXTRACT(EPOCH FROM created_at) * 1000)::BIGINT,
    ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT;

ALTER TABLE audit_events
    ALTER COLUMN occurred_at DROP DEFAULT,
    ALTER COLUMN occurred_at TYPE BIGINT USING (EXTRACT(EPOCH FROM occurred_at) * 1000)::BIGINT,
    ALTER COLUMN occurred_at SET DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT;
